"""empty message

Revision ID: 731b71a628e7
Revises: 
Create Date: 2025-09-11 19:49:57.955699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '731b71a628e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributors_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('distributor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('distr_cat_original_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['distributors_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distributor_name', 'distr_cat_original_id')
    )
    with op.batch_alter_table('distributors_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributors_categories_distr_cat_original_id'), ['distr_cat_original_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributors_categories_distributor_name'), ['distributor_name'], unique=False)
        batch_op.create_index('unique_distributor_category_index', ['distributor_name', 'distr_cat_original_id'], unique=False)

    op.create_table('general_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['general_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('traceable', sa.Boolean(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_id_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'base')
    )
    with op.batch_alter_table('vendor_id_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_id_map_base'), ['base'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_id_map_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('categories_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_category_id', sa.Integer(), nullable=True),
    sa.Column('distributor_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_category_id'], ['distributors_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['general_category_id'], ['general_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('general_category_id', 'distributor_category_id')
    )
    with op.batch_alter_table('categories_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_contents_distributor_category_id'), ['distributor_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_contents_general_category_id'), ['general_category_id'], unique=False)

    op.create_table('distributor_category_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distr_cat_db_id', sa.Integer(), nullable=True),
    sa.Column('distributor_property_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['distr_cat_db_id'], ['distributors_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', 'unit')
    )
    with op.batch_alter_table('distributor_category_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributor_category_properties_distr_cat_db_id'), ['distr_cat_db_id'], unique=False)

    op.create_table('distributors_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distr_cat_db_id', sa.Integer(), nullable=True),
    sa.Column('distributor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('distributor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('minpromtorg', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('traceable', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_order_amount', sa.Float(), nullable=True),
    sa.Column('order_multiplicity', sa.Float(), nullable=True),
    sa.Column('order_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['distr_cat_db_id'], ['distributors_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distributor_name', 'vendor_id')
    )
    with op.batch_alter_table('distributors_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributors_items_distr_cat_db_id'), ['distr_cat_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributors_items_distributor_name'), ['distributor_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributors_items_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('general_items_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_item_id', sa.Integer(), nullable=True),
    sa.Column('general_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['general_category_id'], ['general_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['general_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_items_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_items_categories_general_category_id'), ['general_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_items_categories_general_item_id'), ['general_item_id'], unique=False)

    op.create_table('general_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['general_category_id'], ['general_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('general_category_id', 'name', 'type', 'unit')
    )
    op.create_table('distributors_items_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distributor_item_id', sa.Integer(), nullable=True),
    sa.Column('distr_cat_prop_id', sa.Integer(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['distr_cat_prop_id'], ['distributor_category_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['distributor_item_id'], ['distributors_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributors_items_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributors_items_properties_distr_cat_prop_id'), ['distr_cat_prop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributors_items_properties_distributor_item_id'), ['distributor_item_id'], unique=False)

    op.create_table('general_categories_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_category_id', sa.Integer(), nullable=True),
    sa.Column('general_property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['general_category_id'], ['general_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['general_property_id'], ['general_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_categories_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_categories_properties_general_category_id'), ['general_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_categories_properties_general_property_id'), ['general_property_id'], unique=False)

    op.create_table('general_properties_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_property_id', sa.Integer(), nullable=True),
    sa.Column('distributor_property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_property_id'], ['distributor_category_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['general_property_id'], ['general_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('general_property_id', 'distributor_property_id')
    )
    with op.batch_alter_table('general_properties_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_properties_map_distributor_property_id'), ['distributor_property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_properties_map_general_property_id'), ['general_property_id'], unique=False)

    op.create_table('items_properties_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['general_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items_properties_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_properties_values_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_properties_values_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_properties_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_properties_values_property_id'))
        batch_op.drop_index(batch_op.f('ix_items_properties_values_item_id'))

    op.drop_table('items_properties_values')
    with op.batch_alter_table('general_properties_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_properties_map_general_property_id'))
        batch_op.drop_index(batch_op.f('ix_general_properties_map_distributor_property_id'))

    op.drop_table('general_properties_map')
    with op.batch_alter_table('general_categories_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_categories_properties_general_property_id'))
        batch_op.drop_index(batch_op.f('ix_general_categories_properties_general_category_id'))

    op.drop_table('general_categories_properties')
    with op.batch_alter_table('distributors_items_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributors_items_properties_distributor_item_id'))
        batch_op.drop_index(batch_op.f('ix_distributors_items_properties_distr_cat_prop_id'))

    op.drop_table('distributors_items_properties')
    op.drop_table('general_properties')
    with op.batch_alter_table('general_items_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_items_categories_general_item_id'))
        batch_op.drop_index(batch_op.f('ix_general_items_categories_general_category_id'))

    op.drop_table('general_items_categories')
    with op.batch_alter_table('distributors_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributors_items_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_distributors_items_distributor_name'))
        batch_op.drop_index(batch_op.f('ix_distributors_items_distr_cat_db_id'))

    op.drop_table('distributors_items')
    with op.batch_alter_table('distributor_category_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributor_category_properties_distr_cat_db_id'))

    op.drop_table('distributor_category_properties')
    with op.batch_alter_table('categories_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_contents_general_category_id'))
        batch_op.drop_index(batch_op.f('ix_categories_contents_distributor_category_id'))

    op.drop_table('categories_contents')
    with op.batch_alter_table('vendor_id_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_id_map_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_id_map_base'))

    op.drop_table('vendor_id_map')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_vendor_id'))

    op.drop_table('items')
    op.drop_table('general_categories')
    with op.batch_alter_table('distributors_categories', schema=None) as batch_op:
        batch_op.drop_index('unique_distributor_category_index')
        batch_op.drop_index(batch_op.f('ix_distributors_categories_distributor_name'))
        batch_op.drop_index(batch_op.f('ix_distributors_categories_distr_cat_original_id'))

    op.drop_table('distributors_categories')
    # ### end Alembic commands ###
